print (f'\n===Tabuada===')
x=int(input(f'\nEscreva um número para ver sua tabuada:'))
print('==========================')
print('{} x {} = {}'.format(x , 1 , x*1))
print('{} x {} = {}'.format(x , 1 , x*2))
print('{} x {} = {}'.format(x , 1 , x*3))
print('{} x {} = {}'.format(x , 1 , x*4))
print('{} x {} = {}'.format(x , 1 , x*5))
print ('{} x {} = {}'.format(x , 1 , x*6))
print ('{} x {} = {}'.format(x , 1 , x*7))
print('{} x {} = {}'.format(x , 1 , x*8))
print('{} x {} = {}'.format(x , 1 , x*9))
print('{} x {} = {}'.format(x , 1 , x*10))
print('==========================')