print ('Reajuste Salarial')
s=float(input('Qual é o salário do funcionário?R$'))
a=(s*15/100)
sn=(a + s)
print('Um funcionário que ganhava R${} , com 15% de aumento , passa a receber R${} '.format(s , sn))